"""Report generator: produces JSON and Markdown reports from analysis results."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .models import FailureReport, ReportIndex, ReportEntry

OUTPUT_DIR = Path("reports")
DOCS_DIR = Path("docs/reports")
INDEX_FILE = OUTPUT_DIR / "index.json"


def _severity_emoji(severity: str) -> str:
    return {
        "critical": "C",
        "high": "H",
        "medium": "M",
        "low": "L",
        "unknown": "?",
    }.get(severity, "?")


def _severity_color(severity: str) -> str:
    return {
        "critical": "#dc2626",
        "high": "#ea580c",
        "medium": "#ca8a04",
        "low": "#16a34a",
        "unknown": "#6b7280",
    }.get(severity, "#6b7280")


def _confidence_bar(confidence: int) -> str:
    """ASCII bar for confidence in markdown."""
    filled = confidence // 10
    empty = 10 - filled
    return "█" * filled + "░" * empty


def _generate_markdown(report: FailureReport) -> str:
    """Generate a human-readable Markdown report."""
    lines: list[str] = []

    lines.append(f"# CI Failure Analysis Report")
    lines.append("")
    lines.append(f"**PR**: [#{report.pr_number}]({report.pr_url}) {report.pr_title}")
    lines.append(f"**Author**: {report.pr_author}")
    lines.append(f"**Analyzed**: {report.analyzed_at}")
    lines.append(f"**Failed Jobs**: {len(report.analyses)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for i, run in enumerate(report.runs):
        lines.append(f"## Run {i + 1}: {run.workflow_name}")
        lines.append("")
        lines.append(f"- **Run ID**: `{run.run_id}`")
        lines.append(f"- **Branch**: `{run.branch}`")
        lines.append(f"- **Created**: {run.created_at}")
        lines.append("")

    lines.append("## Analysis Results")
    lines.append("")

    for analysis in report.analyses:
        severity_col = _severity_color(analysis.severity)
        lines.append(f"### <span style='color:{severity_col}'>[{_severity_emoji(analysis.severity)}]</span> {analysis.job_name}")
        lines.append("")
        lines.append(f"- **Severity**: `{analysis.severity}`")
        lines.append(f"- **Confidence**: {_confidence_bar(analysis.confidence)} ({analysis.confidence}%)")
        lines.append(f"- **Conclusion**: `{analysis.conclusion}`")
        lines.append("")

        if analysis.error_snippets:
            lines.append("#### Error Snippets")
            lines.append("")
            for snippet in analysis.error_snippets:
                lines.append("```")
                lines.append(snippet.strip())
                lines.append("```")
                lines.append("")
        else:
            lines.append("*(No error snippets extracted)*")
            lines.append("")

        lines.append("#### Root Cause")
        lines.append("")
        lines.append(analysis.root_cause or "*(No root cause analysis available)*")
        lines.append("")

        if analysis.related_files:
            lines.append("#### Related Files")
            lines.append("")
            for f in analysis.related_files:
                lines.append(f"- `{f}`")
            lines.append("")

        if analysis.fix_suggestions:
            lines.append("#### Fix Suggestions")
            lines.append("")
            for suggestion in analysis.fix_suggestions:
                lines.append(f"- {suggestion}")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(f"*Report generated by ascend-ci-insight on {datetime.now(timezone.utc).isoformat()}*")

    return "\n".join(lines)


def generate_report(report: FailureReport) -> tuple[Path, Path]:
    """Write JSON and Markdown report files. Returns (json_path, md_path).

    Writes to both reports/ (local) and docs/reports/ (GitHub Pages).
    """
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_dir = OUTPUT_DIR / date_str
    report_dir.mkdir(parents=True, exist_ok=True)

    json_path = report_dir / f"pr-{report.pr_number}.json"
    md_path = report_dir / f"pr-{report.pr_number}.md"

    json_content = report.to_json()
    json_path.write_text(json_content, encoding="utf-8")
    md_path.write_text(_generate_markdown(report), encoding="utf-8")

    print(f"  -> {json_path}")
    print(f"  -> {md_path}")

    # Also write JSON to docs/reports/ for GitHub Pages
    docs_report_dir = DOCS_DIR / date_str
    docs_report_dir.mkdir(parents=True, exist_ok=True)
    docs_json = docs_report_dir / f"pr-{report.pr_number}.json"
    docs_json.write_text(json_content, encoding="utf-8")
    docs_json.chmod(0o644)

    return json_path, md_path


def update_index(reports: list[FailureReport]) -> Path:
    """Regenerate the report index file for the dashboard."""
    entries: list[ReportEntry] = []
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    for report in reports:
        top_severity = "low"
        for a in report.analyses:
            sev_order = ["critical", "high", "medium", "low", "unknown"]
            if sev_order.index(a.severity) < sev_order.index(top_severity):
                top_severity = a.severity

        entries.append(ReportEntry(
            pr_number=report.pr_number,
            pr_title=report.pr_title,
            json_path=f"reports/{date_str}/pr-{report.pr_number}.json",
            md_path=f"reports/{date_str}/pr-{report.pr_number}.md",
            analyzed_at=report.analyzed_at,
            failed_job_count=len(report.analyses),
            top_severity=top_severity,
        ))

    # Merge with existing index entries
    existing: dict[int, ReportEntry] = {}
    if INDEX_FILE.exists():
        try:
            import json
            old_data = json.loads(INDEX_FILE.read_text())
            for e in old_data.get("reports", []):
                existing[e["pr_number"]] = ReportEntry(**e)
        except Exception:
            pass

    for e in entries:
        existing[e.pr_number] = e  # Update or add

    merged = sorted(existing.values(), key=lambda x: x.analyzed_at, reverse=True)

    index = ReportIndex(
        generated_at=datetime.now(timezone.utc).isoformat(),
        reports=list(merged),
    )

    INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    INDEX_FILE.write_text(index.to_json(), encoding="utf-8")
    print(f"  Index updated: {INDEX_FILE} ({len(merged)} reports)")

    # Also write to docs/reports/ for GitHub Pages
    docs_index = DOCS_DIR / "index.json"
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    docs_index.write_text(index.to_json(), encoding="utf-8")
    docs_index.chmod(0o644)

    return INDEX_FILE
